- docs/src/index.md
I was reading the getting started page and noticed this link was broken. Looks like it should be a relative path.
> Fix ODE tutorial link

- docs/src/features/monte_carlo.md
Use`@everywhere` to make sure all necessary functions are available to the parallel processes.
Add a second example using multithreading where this is not required due to shared memory. 
Add links to relevant sections of the documentation for further information.
> Updated example 1 parallel Monte Carlo

- docs/src/basics/faq.md
Markdown link syntax was reversed
> Fix link to ODE tutorial in faq

- docs/src/tutorials/bvp_example.md
In `bc2!` the variable `u[1]` is a two-vector, not a scalar. Running the code as is yields a MethodError.
I select the first element of the two-vector in each boundary condition and get the same plot as on the page.
> fix typo on BVP example page

- docs/src/features/performance_overloads.md
The documentation for the DAE Jacobian uses `gamma` differently than the provided example. It's the example, and not the stated version, that appears to work for me.
> Typo in performance_overloads

- docs/src/types/jump_types.md
1. Added note explaining how to create zeroth order reactions
2. Added note explaining that species indices within stoichiometry vectors should be ordered from smallest to largest index.
> JumpProblem - MassActionJump updates

- docs/src/basics/integrator.md
It seems like a change from `userdata` to `p` in the integrator interface hasn't been updated in the documentation. Also, while the other fields are described by their values, `userdata` was described by its type which is slightly odd, so I've adjusted it to describe it by its value.
> Update the integrator interface documentation

- docs/src/features/callback_functions.md
In the `condition` description, I added a reference to the manual page on integrator interface. This is to make it more explicit, since `integrator` is not described until the next bullet point.
> More referencing of integrator interface

- docs/src/basics/integrator.md
The documentation doesn't explicitly name the composite type `DEIntegrator`. It refers mainly to the instance `integrator` (and sometimes `Integrator`). I've therefore added `DEIntegrator` in a few places. (I needed to know because I wanted to set a dispatch pattern for a callback condition.) 
On another note, there is a discrepancy, where the documentation shows the prototype `reinit!(integrator::ODEIntegrator …)`, whereas the code docstring says `reinit!(integrator::DDEIntegrator …`. I suspect these should be made consistent with each other, but I wasn't sure whether it should be `DEIntegrator`/`ODEIntegrator`/`DDEIntegrator`. My guess is `DEIntegrator` since that is most general, and `reinit!` seems to be quite general. But I wasn't sure, so I didn't change it.
> Explicitly naming DEIntegrator in docs

- docs/src/features/performance_overloads.md
Sections about `DAEFunction` and `DDEFunction` seem to be mixed up.
> Correct DAEFunction and DDEFunction sections

- docs/src/solvers/ode_solve.md
Updates for
- https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/543
- https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/537 (#168)
Since the interface and design for `MatrixFreeOperator` is not complete at the moment, I'll refrain from mentioning it in the `LinearExponential` docs for now.
> Update for Exprb and `LinearExponential`

- docs/src/analysis/sensitivity.md
This fixes the fix of #154. :face_with_head_bandage: I took a look on the adjoint equation again today and found that my previous "fix" is wrong. The sign of `\lambda` in the integral
```
\int_{t_{0}}^{T} +\lambda^{\star}(t) f_{p}(t)+g_{p}(t)dt+...
```
is positive, thus, in the equation
```
\frac{d\lambda^{\star}}{dt}=g_{u}(t)-\lambda^{\star}(t)f_{u}(t),\thinspace\thinspace\thinspace\lambda^{\star}(T)=0
```
`g` should be positive, too.
> Fix adjoint SA equation

- docs/src/models/biological.md
1. Documents all fields of the `reaction_network` type.
2. Documents the new `min_reaction_network` type and how to use it with `addodes!` and such.
3. For `addjumps!` documents optional kwargs to control which jumps get constructed.
> update for min_reaction_network and steady-state reaction network problems

- docs/src/features/callback_library.md
Fixes https://github.com/JuliaDiffEq/DiffEqCallbacks.jl/issues/56
Regarding the numerical values, I let the code run and copied the results.
EDIT: I'm such an idiot! 🤣 I overlooked that the initial condition was random, and thought it's fixed. Anyway, the numerical values are not supposed to be reproducible, so either ones should be fine.
> correct SavingCallback docs

- docs/src/basics/integrator.md
- docs/src/basics/solution.md
It seems a new `retcode` is added in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/554. This PR notes that in the documentation.
> Document :Terminated retcode

- .travis.yml
- Project.toml
- REQUIRE
- docs/make.jl
- docs/src/apis/diffeqbio.md
- docs/src/index.md
This adds a new sidebar category for APIs, with a page containing a generated API for `DiffEqBiological` based on the comments I've added there. On my computer the webpages generate fine and look good.
Note, this make DiffEqDocs depend on DiffEqBiological. As the later needs Julia 1.1 I bumped REQUIRE and travis to 1.1.
> DiffEqBiological API

- docs/src/analysis/global_sensitivity.md
Documentation on the global sensitivity analysis is currently quite sparse.
The analysis does not work with models `f` that return a single output. The information that the model needs to output a vector (instead of a single value) would have saved me time. Therefore, I suggest to add it here.
> Document required signature of model f in global_sensitivity.md

- docs/src/solvers/ode_solve.md
Added documentation for ExtrapolationMidpointDeuflhard and ExtrapolationMidpointHairerWanner (cf. https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/714)
> Documentation for explicit extrapolation methods

- docs/src/basics/common_solver_opts.md
I think,
qmin: Defines the **minimum** value possible for the adaptive q. Defaults are algorithm-dependent.
is correct.
> Fix the explanation of qmin

- Project.toml
- docs/make.jl
This doesn't seem to be used for anything and I'm not sure if that package is even maintained anymore. It was restricting `DiffEqBase` to 3.0.0 and preventing the most recent version from being installed.
> Remove DiffEqPDEBase dependency

- docs/make.jl
- docs/src/apis/diffeqbase/callbacks.md
- docs/src/apis/diffeqbase/data_arrays.md
- docs/src/apis/diffeqbase/de_types.md
- docs/src/apis/diffeqbase/ensembles.md
- docs/src/apis/diffeqbase/functions.md
- docs/src/apis/diffeqbase/integrators.md
- docs/src/apis/diffeqbase/interpolation.md
- docs/src/apis/diffeqbase/noise.md
- docs/src/apis/diffeqbase/operators.md
- docs/src/apis/diffeqbase/other.md
- docs/src/apis/diffeqbase/overview.md
- docs/src/apis/diffeqbase/problems.md
- docs/src/apis/diffeqbase/solutions.md
- docs/src/apis/diffeqbase/solvers.md
- docs/src/apis/diffeqbase/utility.md
Created a skeleton for the `DiffEqBase` API documentation. I haven't actually written much content, but there are docstrings added for nearly all types and most functions categorized into different pages and subheadings. I'm hoping having this framework in place will make it easy for people who know the codebase better than I to start filling in the rest.
I created a PR to `DiffEqBase` that added docstring stubs for many types and functions that were lacking them, so until that's accepted you'll get a lot of "no docs found for ..." warnings.
> API documentation skeleton for DiffEqBase

- docs/src/basics/faq.md
Both ForwardDiff.jl and Calculus.jl give me the same answer.
But this answer is slightly different from the result previously in the docs, which was also the same for ForwardDiff.jl and Calculus.jl.
Was this example always wrong?
> time no longer needs to be dual type

- docs/src/features/noise_process.md
I believe there is a mistake here, the Wiener process is not white noise, but rather Brownian (or red) noise. The increments are white Gaussian noise, but the process is not. See [the Wikipedia article](https://en.wikipedia.org/wiki/Wiener_process).
> The Wiener process is not white noise

- docs/src/analysis/sensitivity.md
- the problem has only three parameters hence the fourth dual is no needed and confusing; if the intention was to have an unused component, then the value is p[4] is wrong (it is changed from 1 to 3 for no reason)
- tspan was never defined (but used  in the last code section)
- you need `u0dual` rather than `u0` in the last piece of code, otherwise you will get `TypeError: in typeassert, expected Float64, got Dual{Nothing,Float64,4}`
> Changes in Section `using ForwardDiff.jl`

- docs/src/analysis/sensitivity.md
sol_dual contains the solution and the duals, hence the offset [i+1] is needed to extract the i-th derivative
> extracting partials from sol_dual in `using ForwardDiff.jl`

- docs/src/analysis/sensitivity.md
- the i-th component was promised in the wording thus it should be given in the formula
- since solution is named u(t) everywhere else, the remaining occurrence of y(t) needed to be eliminated
- I am not sure whether the sentence with Jv with AD is clear now. I have added that this is without truncation error (but in the f(d) formula still needed the \approx because higher order terms are omitted).
> change remaining y(t) to u(t) for concistency

- docs/src/analysis/sensitivity.md
dp[i] has very different meaning between case one and case two and the original wording didn't reflect this. In the second case, (sol, i), i is the time step at which the data is returned -- which isn't how I would understand the original text.
> extract_local_sensitivities(sol, i)

- docs/src/analysis/sensitivity.md
I have tried to make the use of formulae more consistent. In particular, the arguments of the functions should be clear, using u(p), u(t), u(t,p) interchangeably is too confusing. There is still more work to do in this direction, however, I would like to see first whether you agree with this PR. The term "functional" should not be used for ``g(u,t,p)`` but for ``G(u,p)`` (not yet edited).
> introduction to adjoint sensitivity analysis

- docs/src/analysis/global_sensitivity.md
This also proposes a few changes to the interface:
- Everything should get the same `p_range` call
- Anything else should end up as keyword arguments in the methods
- Morris should somehow be reduced to an `N`, and then some extra (optional) details in the methods
- Sobol should move its error estimator argument
- Regression needs an interface change
> Restructure GSA documentation

- docs/src/features/ensemble.md
Fixed a redundant `$condition ? true : false` ternary statement and used the extra space to add spaces around binary operators.
> Fix reduction func in ensembles example #3

- docs/src/types/jump_types.md
@TorkelE @isaacsas this was updated awhile ago, but never got upstreamed into DiffEqBio, but now is the time to probably handle it. (This is what throws the warning: it has a fallback so DiffEqBio still works, just not optimally)
> Update RegularJumps documentation for the matrix-free style

- docs/src/analysis/sensitivity.md
Using sum_of_solution(u0,p) to calculate the gradient results in (nothing, nothing) because the non-remade prob was referenced in the solve call.
> Fix Typo in "solve Differentiation Examples"

- docs/src/solvers/ode_solve.md
https://docs.sciml.ai/stable/solvers/ode_solve/#Parallelized-Implicit-Extrapolation-Methods-1
MWE:
```
julia> alg = ImplicitEulerExtrapolation(max_order=7,min_order=4,init_order=4,sequence=:bulirsch)
ERROR: MethodError: no method matching ImplicitEulerExtrapolation(; max_order=7, min_order=4, init_order=4, sequence=:bulirsch)
Closest candidates are:
ImplicitEulerExtrapolation(; chunk_size, autodiff, diff_type, linsolve, max_order, min_order, init_order, threading) at C:\Users\Utkarsh\.julia\dev\OrdinaryDiffEq\src\algorithms.jl:63 got unsupported keyword argument "sequence"
Stacktrace:
[1] kwerr(::NamedTuple{(:max_order, :min_order, :init_order, :sequence),Tuple{Int64,Int64,Int64,Symbol}}, ::Type{T} where T) at .\error.jl:157
[2] top-level scope at REPL[64]:1
```
@ChrisRackauckas
> Broken example in Implicit Extrapolation Methods and typo fix

- docs/src/features/diffeq_operator.md
There is no `DiffEqLinearOperator` AFAIK, so I'm assuming it was meant to say `DiffEqArrayOperator` instead (although I'm actually not sure I'm correct).
> Fix typo in DiffEq Operator docs

- docs/src/solvers/ode_solve.md
The in-code documentation should also be updated with the article, because the only way I could find the source of the `RKO65` method was finding https://github.com/SciML/OrdinaryDiffEq.jl/issues/864 via git blame. I don't know where to do this though.
> Fix typo and attribution for RKO65

- docs/src/solvers/nonautonomous_linear_ode.md
- docs/src/types/nonautonomous_linear_ode.md
This PR contains two minor fixes to the docs:
1. Add the missing footnote for the IOP reference in the `LinearExponential` integrator documentation.
2. Change the section label for the non-autonomous problems section to not be the same as the label for the ODE problems section. The non-autonomous section is actually never referenced, so no places need to be updated with the change (but the ODE section is referenced, so this caused confusion over which section to link to).
Fixes #424
> Add missing footnote and fix duplicated heading

- docs/src/types/dde_types.md
- docs/src/types/dynamical_types.md
Companion documentation PR for https://github.com/SciML/SciMLBase.jl/pull/14
> Add doc for new SecondOrderDDEProblem and DynamicalDDEProblem

- docs/src/solvers/ode_solve.md
Hi, I just added [ProbNumDiffEq.jl](https://github.com/nathanaelbosch/ProbNumDiffEq.jl) to the full list of ODE solvers. This package provides probabilistic numerical ODE solvers, and was developed with compatibility to the DifferentialEquations.jl ecosystem in mind.
Please let me know about any changes I should make to this PR in order to add it to your documentation. And thank you for your feedback!
> Added ProbNumDiffEq.jl to the full list of ODE solvers

- docs/src/features/progress_bar.md
I hope these few changes can point out clearer that `global_logger` should be either called as the very first thing in the `.jl` file or set up in the `startup.jl`. Based on this conversation: https://julialang.zulipchat.com/#narrow/stream/274208-helpdesk-(published)/topic/Progress.20Bar.20in.20Terminal.20with.20DifferentialEquations.2Ejl
> Explicitely mention that global_logger needs to be called first

- docs/src/features/callback_library.md
The documentation seems to be outdated - the signature did not match the convention used in the source code.
> fix calling signature of g for ManifoldProjection

- docs/src/basics/integrator.md
Small error on the order of the return values for `intervals(integrator)` example 
It should be: `uprev, tprev, u, t` ([integrator_interface.jl#L439](https://github.com/SciML/SciMLBase.jl/blob/ca50226c8db0f446fd28e70344f34a86c962aade/src/integrator_interface.jl#L439))
> Fix order of return values in integrator intervals() example

- docs/src/solvers/dynamical_solve.md
- docs/src/types/dynamical_types.md
Some parameters for DynamicalODEProblem and HamiltonianProblem were switched, so I reordered them to match the source code.
It should fix this [issue](https://github.com/SciML/DiffEqDocs.jl/issues/451)
> fix order of parameters for DynamicalODEProblem and HamiltonianProblem

- docs/src/solvers/ode_solve.md
This documents the new low-storage schemes added in https://github.com/SciML/OrdinaryDiffEq.jl/pull/1384.
> document new low-storage schemes

- docs/src/solvers/ode_solve.md
- adding descriptions of step_limiter! and stage_limiter! to reflect https://github.com/SciML/OrdinaryDiffEq.jl/pull/1293 and https://github.com/SciML/OrdinaryDiffEq.jl/pull/1427
- Added SSPRK43 (SSPRK432's docstrings suggest using it, but it’s missing from the descriptions)
- Replaced HSLDDRK64 with SHLDDRK64. HSLDDRK64 is noted as deprecated in favor of SHLDDRK64 , but the suggested methods are not listed on DiffEqDocs.jl.
- limiter(u,f,t) -> limiter(u,f,p,t)
> updating ODE solver method docs

- docs/src/analysis/parameter_estimation.md
Turing evidently renamed their tutorial pages.
> Fix broken link

- docs/src/features/progress_bar.md
https://c42f.github.io/TerminalLoggers.jl/stable/#Installation-and-setup-1 is not a valid link anymore.
> TerminalLoggers site change c42f -> JuliaLogging

- docs/src/basics/common_solver_opts.md
estimatoes sounds like a delicious variety of tomatoes, but unfortunately for us all the correct spelling is estimates
> Typo in common_solver_opts

- docs/src/features/linear_nonlinear.md
From discussion on slack, Rosenbrock integrators will reuse the `A` later, so it shouldn't be modified by the linear solver
> Another fix to the linsolve example

- docs/src/basics/overview.md
Pretty straightforward, fixed two links. I've identified others, but I'm leaving that for another day/issue. As background, this was referenced in #513 .
> Corrected prominent links to developer documentation in overview

- docs/src/types/ode_types.md
The ODE type ```prob_ode_vanstiff``` has changed to ```prob_ode_vanderpol_stiff```.
See:
https://github.com/SciML/DiffEqProblemLibrary.jl/blob/e1232b3ef6f29f5894d7164090ca54d4267a6e56/src/ode/ode_simple_nonlinear_prob.jl#L90
> Fix ode type vanderpol_stiff

- docs/src/solvers/rode_solve.md
When we are using `RandomEM` solver, we need to specify `dt`
> Add dt for RandomEM example usage in RODE Solvers

- docs/src/analysis/sensitivity.md
For users it might not be obvious enough from the current note how ForwardDiff is handled differently from other AD libraries.
> Explanation sensealg with ForwardDiff

- docs/src/types/ode_types.md
Small modification to make it clearer for newcomers on the two main ways of specifying `f`. This is particularly relevant when working with non mutating AD packages such as Zygote. Until now, it was not obvious how to specify `f` if we cannot mutate an array.
Feel free to add any corrections on how to best integrate it to flow better.
> Clarify ways of specifying `f`

- docs/src/features/ensemble.md
- docs/src/tutorials/sde_example.md
These are minor documentation clarification concerning Ensemble problems. If an SDE problem contains a custom noise process, `safetycopy` is insufficient for properly setting up multiple trajectories. The previous version of the documentation was not clear about that, leading to confusion like this one: https://discourse.julialang.org/t/sde-ensembleproblem-unhappy-with-trajectories-2/82098
> EnsembleProblem safetycopy clarification

- docs/src/solvers/sde_solve.md
This replaces the term `multi-dimensional` by `non-diagonal` noise for the SROCK solvers.
Everywhere else only `non-diagonal` is used so I suspect they are equivalent?
> Fix notation for non-diag. noise in SDE Solvers

- docs/src/solvers/dynamical_solve.md
In PR [OrdinaryDiffEq.jl#1831](https://github.com/SciML/OrdinaryDiffEq.jl/pull/1831) and PR [OrdinaryDiffEq.jl#1832](https://github.com/SciML/OrdinaryDiffEq.jl/pull/1832), new Runge-Kutta-Nyström methods DPRKN5 and ERKN7 are added.
This PR adds the corresponding docs.
> Add docs for DPRKN5 and ERKN7

- docs/src/types/dae_types.md
Fixes `importdaeproblems not defined` error. `DAEProblemLibrary` does not export this function. 
Made the doc more self-sustained by adding `using Sundials`.
> Update DAE Problems documentation

- docs/src/features/ensemble.md
- docs/src/solvers/dae_solve.md
- docs/src/solvers/dynamical_solve.md
- docs/src/solvers/nonautonomous_linear_ode.md
- docs/src/solvers/ode_solve.md
Track https://github.com/SciML/OrdinaryDiffEq.jl/pull/1888, https://github.com/SciML/OrdinaryDiffEq.jl/pull/1921 and https://github.com/SciML/OrdinaryDiffEq.jl/pull/1898
> Add docs for SIR54, CG4a and Alshina methods

- docs/src/extras/timestepping.md
See also https://github.com/SciML/StochasticDiffEq.jl/pull/522.
> Add custom/abstract controller description

- docs/src/tutorials/faster_ode_example.md
Link was broken on valuable resource, I would've left it alone but it took me a couple googles to find.
old link: https://biojulia.net/post/hardware/
new link: https://biojulia.dev/post/hardware/
> updating path for biojulia reference

- README.md
The link in the README points to the old documentation URL. This PR updates the documentation link to `sciml.ai`. I get a "Forbidden Code" when I try to access the development version of the docs, I assume that's intentional? I'm going to remove the `/dev` suffix from the URL too.
> Updating documentation link

- docs/src/basics/solution.md
This note was written 4 years ago.
From talking to @ChrisRackauckas  the majority of them are now implemented.
So we should update the docs so people's default assumption is that things will work.
> update docs to state most derivatives have been implemented

- docs/src/solvers/dae_solve.md
Updates it for https://github.com/SciML/OrdinaryDiffEq.jl/pull/2048#pullrequestreview-1774020684
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [ScioML Style Guide](https://github.com/SciML/SciMLStyle) and
> Improve DAE solver discussion of interpolations

- docs/src/tutorials/sde_example.md
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [ScioML Style Guide](https://github.com/SciML/SciMLStyle) and
> Minor improvements in the documentation (sde_example.md)

- docs/src/tutorials/sde_example.md
Used `!` in functions, slight modification of the text.
> More minor updates

- docs/src/tutorials/sde_example.md
@ChrisRackauckas I am just rewriting parts of the documentation as I read along. Mostly rephrasing things I find confusing at first read.
I need your input for the following. Specifying `adaptive = false` in `solve` turns off adapting time step over the course of numerical integration, but it still chooses the initial time step on it's own right?
> Minor improvements

- .github/workflows/FormatCheck.yml
Update the workflows in this repository to use SciML's reusable workflows.
This is part of a larger effort to standardise the SciML's CI workflows for more generic and common requirements, to keep the workflows uniform and easier to maintain.
> ci: standardise workflows using SciML's reusable workflows

- docs/src/solvers/ode_solve.md
> changes Scholz47 to Scholz4_7 to match the method name in OrdinaryDiffEq

- docs/src/solvers/split_ode_solve.md
> fix link to Sundials in split ODE solver docs

- docs/src/tutorials/sde_example.md
I believe there's a small mistake in this example as the equation uses `σ` but in the code we use `θ` (in two places instead of one).
I fixed the consistency with the equations but the functions don't actually make much sense as I see it as `f` and `g` should really be using `p` instead of some global variables `μ`, `κ`, `θ`, `σ` if I'm not mistaken.
> fix: Update sde_example.md

- docs/src/basics/solution.md
- docs/src/solvers/bvp_solve.md
Add the docs for new Lobatto and Radau methods
> Add FIRK docs

- docs/src/basics/integrator.md
It's [not a kwarg](https://docs.sciml.ai/DiffEqDocs/stable/basics/integrator/#CommonSolve.step!). Please feel free to reword my changes to the text to make it clearer.
> Fix step! call in documentation

- docs/src/basics/plot.md
Multi-line lists in markdown are expected to be indented, otherwise the list ends prematurely and then restarts.
(None applicable, only documentation page modified)
> Fix markdown list in plot.md

- docs/src/examples/classical_physics.md
The code example about radioactive isotopes does not correctly represent the physics. They decay as $2^{-t / t_{1/2}}$, not $\exp(-t \times t_{1/2})$.
This PR corrects the differential equation and the analytical solution.
Also, the vertical axis of the plot is not in percentage.
(Radioactive decay is a quantum phenomenon, by the way :) )
> Correct physics of C14 example

- docs/src/types/bvp_types.md
- docs/src/types/dae_types.md
- docs/src/types/dde_types.md
- docs/src/types/ode_types.md
- docs/src/types/rode_types.md
- docs/src/types/sdde_types.md
- docs/src/types/sde_types.md
- docs/src/types/steady_state_types.md
> Add alias specifier docstrings to problem type pages 

- docs/src/basics/solution.md
Based on comments from https://github.com/SciML/Catalyst.jl/pull/1248
> Add more details to the indexing interface page

- docs/make.jl
- docs/src/tutorials/sde_example.md
I tried to polish the explanation of the diagonal vs non-diagonal noise in SDE examples. In particular, I found it confusing that the function `g` in the code for the diagonal noise returned/modified a vector, while the equally named g in the equation was a matrix. That the function implicitly returns/modifies a diagonal of the matrix was a fact that could have escaped one's attention. I do confirm that it was stated in the documentation but I just tried to emphasise it even more.
While working on the rewording, I also replaced in the codes the names of in-place functions `f` and `g` with `f!` and `g!`. I hope this will not be found as annoying nitpicking. As I am checking other examples in DifferentialEquations.jl, while some obviously follow this convention, majority does not.
> SDE Examples: minor rewording of explanation of "diagonal vs non-diagonal noise"

- docs/src/solvers/dae_solve.md
See https://github.com/SciML/OrdinaryDiffEq.jl/issues/2513, https://github.com/SciML/OrdinaryDiffEq.jl/pull/2602, https://github.com/SciML/OrdinaryDiffEq.jl/pull/2698, https://github.com/SciML/OrdinaryDiffEq.jl/issues/2594
Will wait until those are more or less resolved before making more changes here.
> Add some more details about DAE and mass matrix

- docs/src/features/progress_bar.md
> remove outdated reference to juno

- docs/src/types/bvp_types.md
The docstring for `BVPFunction` currently doesn't appear anywhere on the docs site.
None applicable
This PR puts the docstring for the `BVPFunction` type in the context of the documentation website.
> Add docstring for `BVPFunction` to bvp_types.md

- docs/src/features/dae_initialization.md
- Replace all `BrownBasicInit` references with `BrownFullBasicInit` in the DAE initialization documentation
- Updates documentation to align with the new API
- DiffEqBase PR #1216: Removes BrownBasicInit alias, keeps only BrownFullBasicInit
- OrdinaryDiffEq PR #2873: Updates to use only BrownFullBasicInit  
- Sundials.jl: Updates to use only BrownFullBasicInit
- Updated all code examples to use `BrownFullBasicInit()`
- Updated docstring reference from `DiffEqBase.BrownBasicInit` to `DiffEqBase.BrownFullBasicInit`
- Updated table entry and comments to reflect the new name
> Update documentation to use BrownFullBasicInit
