docs/src/analysis/parameter_estimation.md
docs/src/analysis/parameterized_functions.md
docs/src/analysis/uncertainty_quantification.md
docs/src/basics/common_solver_opts.md
docs/src/basics/integrator.md
docs/src/basics/overview.md
docs/src/basics/plot.md
docs/src/basics/solution.md
docs/src/features/callback_functions.md
docs/src/features/monte_carlo.md
docs/src/features/output_specification.md
docs/src/features/performance_overloads.md
docs/src/features/progress_bar.md
docs/src/index.md
docs/src/solvers/dae_solve.md
docs/src/solvers/fempoisson_solve.md
docs/src/solvers/ode_solve.md
docs/src/tutorials/dde_example.md
docs/src/tutorials/femheat_example.md
docs/src/tutorials/fempoisson_example.md
docs/src/tutorials/femstochastic_example.md
docs/src/tutorials/ode_example.md
docs/src/tutorials/sde_example.md
docs/src/types/dae_types.md
docs/src/types/dde_types.md
docs/src/types/fem_types.md
docs/src/types/ode_types.md
docs/src/types/sde_types.md

Minor typographical fixes to the documentation.

Mfiano patch 1

---

docs/src/tutorials/ode_example.md

Fixed some minor mistakes relating to dependent and independent variables.

Fixed typos in ode_example 

---

docs/src/analysis/parameter_estimation.md

result.minimum[1] returns the minimum value of the objective function whereas result.minimizer[1] returns that value of the variable at which the minimum occurs.

Fixed typo in parameter_estimation.md

---

docs/src/solvers/ode_solve.md

Added documentation for the new strong stability preserving Runge-Kutta methods.

added documentation for SSPRK22, SSPRK33, and SSPRK104

---

docs/src/index.md

added low dependency on Home

---

docs/src/solvers/dde_solve.md

The keywords of the MethodOfSteps algorithm are outdated.

Update keywords of DDE solver

---

docs/src/features/callback_library.md

This is my current work on an updated documentation of callbacks as suggested in https://github.com/JuliaDiffEq/DiffEqDocs.jl/issues/37. Should probably only be merged after a new release of DiffEqCallbacksLibrary.

Update documentation of callback library

---

docs/src/solvers/ode_solve.md

This should only be merged once we merge the corresponding OrdinaryDiffEq changes as well.

Update finite differencing option description

---

docs/src/solvers/ode_solve.md

see https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/174

Added SSPRK54

---

docs/src/solvers/dde_solve.md
docs/src/tutorials/dde_example.md

I tried to update the documentation of DDEs, I hope it covers the most relevant aspects.

Update DDE documentation

---

docs/src/analysis/parameter_estimation.md
docs/src/analysis/parameterized_functions.md
docs/src/features/callback_functions.md
docs/src/features/callback_library.md
docs/src/features/monte_carlo.md
docs/src/features/noise_process.md
docs/src/features/performance_overloads.md
docs/src/solvers/dde_solve.md
docs/src/solvers/ode_solve.md
docs/src/tutorials/dae_example.md
docs/src/tutorials/discrete_stochastic_example.md
docs/src/tutorials/jump_diffusion.md
docs/src/tutorials/ode_example.md
docs/src/tutorials/rode_example.md
docs/src/tutorials/sde_example.md

Clean up old style function definitions. A couple typos as well.

---

docs/src/features/monte_carlo.md

🖍 typo fix

---

REQUIRE
docs/make.jl
docs/src/features/callback_library.md

Also fix a typo and require DiffEqProblemLibrary.

Add PeriodicCallback docs

---

docs/src/index.md

Algebraic differential equation can often mean something else.

Change algebraic differential to differential algebraic

---

docs/src/solvers/ode_solve.md

Requires https://github.com/PerezHz/TaylorIntegration.jl/pull/44

Add TaylorIntegration.jl

---

docs/src/basics/integrator.md

I guess that's what you mean in this context.

Fix two possible typos: integrator -> iterator

---

docs/src/basics/integrator.md

Document changes in:
- https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/86
- https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/256
- https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/253

Document set_{t,u,ut}!

---

docs/make.jl
docs/src/basics/problem.md
docs/src/basics/structs.md
docs/src/index.md

closes #84 
blocked by https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/92
Not sure the second commit about SplitFunction is worth mentioning it, though. Does anybody want to change SplitFunction?

Document remake

---

docs/src/solvers/split_ode_solve.md
docs/src/types/split_ode_types.md

Documentation update for the exponential integrators

---

docs/src/features/performance_overloads.md

The in-place functions write into the first variable. Also, the analytical solution does not write into anything.

Documentation tweak

---

docs/src/solvers/sde_solve.md

Updated notes to include the matrix form of ggprime for PCEuler. 
Also found some mistakes where bbprime was used instead of ggprime

Updated sde_solve.md

---

docs/src/solvers/split_ode_solve.md

Minor update to reflect changes in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/274

Exponential integrators update

---

docs/src/types/dynamical_types.md

Brought the documentation in accordance with tests and actual interfaces.
Also corrected the remark upon the quadratic form of the `du/dt` function.

corrected definitions of the objective functions

---

docs/src/basics/integrator.md

fixed a typo

---

docs/src/tutorials/dde_example.md
docs/src/types/dde_types.md

This PR updates history functions in the DDE documentation to the new interface with parameters.

Update history function in DDE docs

---

docs/src/basics/integrator.md

https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/276

Document check_error(integrator) interface.

---

docs/src/features/performance_overloads.md

Completes http://docs.juliadiffeq.org/latest/features/performance_overloads.html#Specifying-Jacobian-Types-1.

Section: specifying jacobian prototype

---

docs/src/models/biological.md

Example fix:
ODEproblem -> ODEProblem

typo fix: biological.md

---

docs/src/features/diffeq_arrays.md

Change keyword type to mutable struct

---

docs/src/types/ode_types.md

Fix https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/366

Fix broken link

---

.gitignore
.travis.yml
Project.toml
docs/make.jl

Implement:
https://discourse.julialang.org/t/psa-use-a-project-for-building-your-docs/14974
https://discourse.julialang.org/t/psa-documenter-jl-breaking-changes-version-capping/16431

Setup Documenter using Project.toml

---

docs/src/solvers/steady_state_solve.md

which is added in https://github.com/JuliaDiffEq/SteadyStateDiffEq.jl/pull/8

Document tspan option for DynamicSS

---

docs/src/solvers/dynamical_solve.md

See https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/578#issuecomment-449631911

Fix typo in dynamical solvers

---

docs/src/solvers/bvp_solve.md
docs/src/solvers/dae_solve.md
docs/src/solvers/ode_solve.md
docs/src/solvers/rode_solve.md
docs/src/solvers/sde_solve.md
docs/src/solvers/steady_state_solve.md

Addressed in #184 , this fixes the issue with depth of 2. We can either have a depth of 2:
or we can have depth of 3:
Currently the depth is set to 2. We can change it accordingly.

Fixes Indenting

---

docs/src/models/biological.md

1. Expand the DiffEqBiological examples to show how to solve a larger collection of problem types.
2. Document the `hillr` and `mmr` functions.
3. Fix a typo in the dimerization example ODEs.

expand the set of examples and fix some typos

---

docs/src/solvers/ode_solve.md

@ChrisRackauckas Docs for new DGLDDRK methods.
`DGLDDRK73_C`
`DGLDDRK84_C`
`DGLDDRK84_F`

Added new methods

---

docs/src/solvers/ode_solve.md

Cf. JuliaDiffEq/OrdinaryDiffEq.jl#648 and JuliaDiffEq/OrdinaryDiffEq.jl#658.

add ParsaniKetchesonDeconinck3S*

---

docs/src/analysis/parameter_estimation.md

Fixed typos in the parameter estimation documentation.

Fixed typos

---

docs/src/solvers/ode_solve.md

Cross Ref: JuliaDiffEq/OrdinaryDiffEq.jl#691

Adds docs for Williamson Wrapper optimization

---

docs/src/models/biological.md

Change "(S_i-(n_i+1))" to "(S_i-n_i+1)" to give correct equation

Fix in biological.md

---

REQUIRE
docs/make.jl
docs/src/apis/diffeqbio.md

1. Add three new DiffEqBiological API functions. This should be it for a while I think.
2. ~Updated `makedocs` per the depreciation warning to use `Documenter.HTML()` instead of `:html`.~
2 apparently requires a newer Documenter version...

Update DEBio api 

---

docs/src/types/sde_types.md

@ChrisRackauckas Found some formatting discrepancies while I was going through the docs.

Fix Formatting

---

docs/src/tutorials/sde_example.md

sparse!(A) does not seem to exist...

changed sparse(A) by A=sparse(A)

---

docs/src/analysis/sensitivity.md

Add missing i

---

docs/src/features/callback_functions.md

I have added documentation for now, will add an example of bouncing ball with two walls as an example.

Adds VectorContinuousCallback documentation

---

docs/src/solvers/ode_solve.md
docs/src/solvers/sde_solve.md

Docs for ODE and SDE solvers

---

docs/src/features/linear_nonlinear.md

Start updating linsolve docs

---

docs/src/features/linear_nonlinear.md

See also here: https://stackoverflow.com/questions/54545738/solve-the-heat-equation-with-non-zero-dirichlet-bcs-with-implicit-euler-and-conj/54545739#comment100407633_54545739

Add kwargs to linsolve documentation

---

docs/src/basics/common_solver_opts.md

Minor spelling error

---

docs/src/solvers/sde_solve.md

@ChrisRackauckas please have a look at it.

SKenCarp warning

---

docs/src/solvers/ode_solve.md

update QuDiffEq in ODE solvers

---

docs/src/analysis/uncertainty_quantification.md
docs/src/solvers/ode_solve.md

Some links are broken, implicit Adams Bashforth methods are not documented. Can someone provide me with a description of CNAB2 and CNLF2?
@ChrisRackauckas @YingboMa

NLSolver Documentation

---

docs/src/analysis/bifurcation.md

rclewley's page on gsu has moved. I think this is an equivalent page.

Fix broken link to gsu

---

docs/src/tutorials/jump_diffusion.md

coupled_prob probably was meant to be prob_coupled

updated coupled problem solve code

---

docs/src/tutorials/ode_example.md

Tipped off from this [Discourse topic](https://discourse.julialang.org/t/in-place-functions-in-definition-of-odeproblem-differentialequations/30029)

Correct naming convention for in-place functions

---

docs/src/tutorials/ode_example.md

fix link for ensemble page in ode tutorial

---

docs/src/basics/faq.md
docs/src/basics/problem.md
docs/src/features/performance_overloads.md
docs/src/tutorials/advanced_ode_example.jmd
docs/src/tutorials/dae_example.md
docs/src/types/bvp_types.md
docs/src/types/dae_types.md
docs/src/types/dde_types.md
docs/src/types/discrete_types.md
docs/src/types/dynamical_types.md
docs/src/types/ode_types.md
docs/src/types/rode_types.md
docs/src/types/sde_types.md
docs/src/types/split_ode_types.md
docs/src/types/steady_state_types.md

Fixes https://github.com/JuliaDiffEq/DiffEqDocs.jl/issues/265 https://github.com/JuliaDiffEq/DiffEqDocs.jl/issues/254 https://github.com/JuliaDiffEq/DiffEqDocs.jl/issues/82

massive documentation update

---

docs/make.jl

Add redirect for old links

---

docs/make.jl

https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/529#issuecomment-557468328

Add canonical link for search engines

---

docs/src/solvers/split_ode_solve.md

Fix https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/1005

Remove GenericIIF1, GenericIIF2, Exprb32, and Exprb43

---

docs/make.jl
docs/src/analysis/sensitivity.md
docs/src/extras/sensitivity_math.md
docs/src/index.md

- Focus high level on `concrete_solve`
- Document the `SensitivityAlgorithm` choices
- All adjoints return u0 derivatives
- Put the lower level interfaces below, and explain when they might be useful

Overhaul the sensitivity analysis page

---

docs/src/analysis/parameter_estimation.md

Correct indentation and add api

Update parameter estimation multiple shooting docs

---

docs/src/analysis/global_sensitivity.md

update GSA Regression docs

---

docs/src/tutorials/advanced_ode_example.md

Can you add references for these and the other equations in the docs?

Rosenbrock -> Rober

---

docs/src/tutorials/advanced_ode_example.md

also rearrange the example code to match the equation better

Mass matrix example: fix index

---

docs/src/basics/common_solver_opts.md

Mention `merge_callbacks`

---

docs/src/analysis/structural_estimation.md

SInDy, ISInDy, DMD and examples

Added more documentation

---

docs/src/tutorials/dae_example.md

Small fixes to the DAE example page

---

docs/make.jl

We need to push the documentation forcefully after it started to fail (After change to SciML)

Fix Missing Documentation

---

docs/src/solvers/sde_solve.md

I also started with the recommended method part.. Is there a way to preview the final look of the website?

added description for DRI1 and RI1

---

docs/src/solvers/sde_solve.md

This adds the new methods from https://github.com/SciML/StochasticDiffEq.jl/issues/182

new weak methods

---

docs/src/solvers/sde_solve.md

Forgot about those two important special cases.

specialized versions of DRI1 and PL1WM

---

docs/src/features/diffeq_operator.md

Fix spelling error

---

docs/src/solvers/ode_solve.md

@ChrisRackauckas I have updated the docs. Please have a look.

Update Parallel Extrapolation Docs

---

docs/src/solvers/jump_solve.md

This functionality was introduced in https://github.com/SciML/DiffEqJump.jl/pull/120

Reflect support of callbacks for SSAStepper

---

docs/src/basics/solution.md

Added docs for `sol.destats` for viewing internal statistics to the "special fields" section.

Added notes for solution statistics `sol.destats`

---

docs/src/analysis/sensitivity.md

Per the discussion here: https://github.com/SciML/DiffEqSensitivity.jl/issues/306#issuecomment-660398570.

Add bit explaining the diff-thru-the-solver algos

---

docs/src/features/diffeq_operator.md
docs/src/solvers/split_ode_solve.md

See, e.g., https://en.wikipedia.org/wiki/Phyllis_Nicolson

Fix Nicolson name

---

docs/src/tutorials/bvp_example.md

The Julia code and the supporting text were not consistent, the text was updated to match the Julia code.

Resolve an inconsistency in the pendulum example

---

docs/src/solvers/ode_solve.md

ode_solve: Fix typo

---

docs/src/solvers/nonautonomous_linear_ode.md

added an example for constant matrix A linear ode problem

add example to linear problems documentation

---

docs/src/extras/sensitivity_math.md

Update dead link in sensitivity_math.md

---

docs/src/analysis/sensitivity.md

Also two minor changes to the math. I hope it looks alright.

Fixes to make adjoint_sensitivity example run

---

docs/src/features/callback_library.md

PeriodicCallback default argument

---

docs/src/analysis/sensitivity.md

Fix spelling mistake

---

docs/Project.toml
docs/make.jl
docs/src/basics/common_solver_opts.md
docs/src/extras/timestepping.md

Companion PR to https://github.com/SciML/OrdinaryDiffEq.jl/pull/1384. That PR needs to be merged first.

document new controllers

---

docs/src/extras/timestepping.md

I fixed a type I introduced earlier, sorry. It might be nice to make a new release of the docs once this is fixed.

fix IController name

---

docs/src/solvers/dde_solve.md

FPFunctional was replaced with NLFunctional a while ago.

Replace FPFunctional with NLFunctional

---

docs/src/features/callback_functions.md

Fixes https://github.com/SciML/DifferentialEquations.jl/issues/696

Add tutorial on exact callback handling and accumulation points

---

docs/src/solvers/ode_solve.md

Reflects changes of https://github.com/SciML/OrdinaryDiffEq.jl/pull/1445

update docs on stage/step limiters

---

docs/src/solvers/dae_solve.md

IDA supports left preconditioning only.
https://github.com/SciML/Sundials.jl/issues/317
https://github.com/SciML/Sundials.jl/pull/319

IDA remove prec_side option

---

docs/src/analysis/sensitivity.md

I was not able to run the code in the existing code block. But with the proposed modifications I am able to compute the gradient with the four proposed libraries. I hope that the changes correspond to the recommended way to compute discrete sensitivities, otherwise please let me know if I should include more changes to the PR.

Updated a codeblock on discrete sensitivities

---

docs/src/analysis/sensitivity.md

first draft. Should `ForwardLSSProblem`, `AdjointLSSProblem`, and `NILSSProblem` be described in more detail?

Add docs for shadowing methods

---

docs/src/solvers/dae_solve.md
docs/src/solvers/ode_solve.md

New links taken from here:
https://computing.llnl.gov/projects/sundials/sundials-software

fix broken links

---

docs/src/types/ode_types.md

will this just work or do i need to change a compat somewhere

add strange attractor odes

---

docs/src/solvers/dae_solve.md
docs/src/solvers/ode_solve.md

@yingboma I think it's time we at least add it.

add FBDF to the documentation

---

docs/src/basics/faq.md

integrator interface has changed since this was last written

correct error in integrator interface use

---

docs/src/solvers/dae_solve.md

Rodas5 new interpolation

---

docs/src/features/linear_nonlinear.md

fix link to advanced ode example

---

docs/src/solvers/sde_solve.md

Should be merged after https://github.com/SciML/StochasticDiffEq.jl/pull/459.
@fkastner It would be great if you could quickly review this as well  :)

update docs for stochastic iterated integrals

---

docs/src/tutorials/advanced_ode_example.md

I came across a few small typos in the problem definition.
Cheers, Flemming

typo fixes in brusselator problem definition

---

docs/src/tutorials/rode_example.md

The current link was broken. This PR fixes it.

Adjust a single link in rode_example.md

---

docs/src/features/io.md

Misprint eaxmple -> example

---

docs/src/tutorials/ode_example.md

(Feel free to close, edit or merge without discussion)

ode_example: tweak some basics about simulating ODEs

---

docs/src/tutorials/faster_ode_example.md

Added bangs "!" to mutating derivative and Jacobian functions for consistency and to adhere to the conventions.

Docs: Added bangs "!" to mutating functions

---

docs/src/solvers/jump_solve.md
docs/src/tutorials/discrete_stochastic_example.md

Apply renaming of DiffEqJump to JumpProcesses as by https://github.com/SciML/JumpProcesses.jl/releases/tag/v9.0.0

Update DiffEqJump -> JumpProcesses

---

.gitignore
docs/src/analysis/uncertainty_quantification.md
docs/src/basics/integrator.md
docs/src/basics/plot.md
docs/src/features/callback_functions.md
docs/src/features/ensemble.md
docs/src/tutorials/ode_example.md
docs/src/tutorials/sde_example.md

Should wait for https://github.com/SciML/SciMLBase.jl/pull/211 and a new SciMLBase release.

vars to idxs for plots

---

docs/src/types/ode_types.md

See also this issue:
https://github.com/SciML/DiffEqProblemLibrary.jl/issues/96
and this PR in DiffEqProblemLibrary.jl:
https://github.com/SciML/DiffEqProblemLibrary.jl/pull/97

Correct spelling of Lotka-Volterra

---

docs/src/basics/faq.md

This is a followup to the discussion from https://github.com/SciML/OrdinaryDiffEq.jl/issues/1746

add sparse jacobian section to FAQ

---

docs/src/basics/integrator.md

Based on the Slack conversation with @ChrisRackauckas

document `SciMLBase.unwrapped_f(integrator.f.f)`

---

docs/src/basics/faq.md

The link for index reduction tools is broken. I believe it is this one that we should be redirected to.

Correct a broken link in FAQ section.

---

docs/src/index.md

See https://github.com/SciML/DiffEqDocs.jl/issues/648

Restructuring citation section of docs

---

docs/src/solvers/dynamical_solve.md

Some consistensy could problably be worked harder on. But this form also needs documentation.

Add example for SecondOrderODEProblem

---

docs/src/solvers/ode_solve.md

I added a missing backtick 
\`

Fix Markdown Syntax of `ode_solve.md`

---

docs/make.jl
docs/src/solvers/split_ode_solve.md

This PR fixes the BVP test problems docstrings

Fix BVProblemLibrary docs

---

docs/src/solvers/bvp_solve.md
docs/src/solvers/ode_solve.md

Update some recent BVP developments

Update BVP docs

---

docs/src/features/callback_functions.md

Fixes https://github.com/SciML/DiffEqDocs.jl/issues/681

Fix dividing cell example

---

docs/src/features/progress_bar.md
docs/src/tutorials/sde_example.md
docs/src/types/sdae_types.md

Update ```SDEProblem``` constructor usage in docs

Update SDEProblem usage in docs

---

docs/src/solvers/bvp_solve.md
docs/src/tutorials/bvp_example.md
docs/src/tutorials/rode_example.md
docs/src/tutorials/sde_example.md

Update recent developments in BVP solvers

Update BVP solvers docs

---

docs/src/solvers/ode_solve.md

stop recommending `Rodas4`

---

docs/make.jl

Allow some links

---

docs/src/basics/solution.md

Adds docs for the `strip_solution` function.

strip_solution description

---

docs/src/features/io.md

Adds a quick explanation of `strip_solution` to the JLD2/BSON serialization docs.

add strip_solution to io docs

---

docs/src/features/ensemble.md

- [-] Appropriate tests were added
- [-] The new code follows the
- [-] Any new documentation only uses public API
There is a typo in documentation. This PR aims to fix it.

Fix variable name u_data -> u_init

---

docs/src/basics/solution.md
docs/src/solvers/split_ode_solve.md

CNLF2 is the correct name, see: https://github.com/SciML/OrdinaryDiffEq.jl/blob/88c140752f9d9f11c0fdc4c69bbb8aef162d19ac/lib/OrdinaryDiffEqIMEXMultistep/src/alg_utils.jl#L4

changed CNLF to CNLF2
